# Publish this application to bluemix using ansible
---
- name: Publish the app to Bluemix using Ansible
  hosts: localhost
  connection: local
  vars:
    pipeline_id: "{{ lookup('env','PIPELINE_ID') }}"
    app_hostname: "{{ lookup('env','APP_HOSTNAME') | default(pipeline_id,true) }}"
  tasks:
    - name: CF Push Application
      shell: "cf push -f manifest.yml -u none --hostname {{ app_hostname }}"
