# Publish this application to bluemix using ansible
---
- name: Publish the app to Bluemix using Ansible
  hosts: localhost
  connection: local
  tasks:
    - name: CF Push downloaded build
      shell: "cf push -f manifest.yml -u none"
